name: fumingcube
version: '1.0'
summary: summary
description: description

grade: stable
confinement: strict

apps:
  fumingcube:
    command: fumingcube

parts:
  fumingcube:
    plugin: qmake
    qt-version: qt5
    source: https://github.com/FrankMamuda/fumingcube.git
    
